import Link from "next/link";

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><Link className="landing-brand" href="/">Stellar<span>Remit</span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#why-stellar">Why Stellar</a><Link href="/login">Sign in</Link><Link className="button landing-button" href="/register">Explore the MVP</Link></div></nav>
    <section className="landing-hero"><div className="hero-copy"><div className="eyebrow">Open-source · Stellar testnet</div><h1>Move value across borders with clarity.</h1><p>A simple remittance foundation for African families, freelancers, and small businesses. Explore wallets, balances, and payment flows without touching real-world funds.</p><div className="hero-actions"><Link className="button" href="/dashboard">Open dashboard</Link><a className="button secondary" href="#how-it-works">See how it works</a></div><p className="hero-disclaimer">Testnet prototype. No real money is processed.</p></div><div className="hero-orbit"><div className="orbit-line orbit-line-one" /><div className="orbit-line orbit-line-two" /><div className="hero-card"><span className="pill">● Stellar testnet</span><strong>Send with confidence</strong><div className="hero-card-row"><span>Estimated fee</span><b>0.00001 XLM</b></div><div className="hero-card-row"><span>Settlement</span><b>Fast &amp; public</b></div></div></div></section>
    <section className="landing-strip" id="how-it-works"><div><strong>01</strong><span>Create or connect a testnet wallet</span></div><div><strong>02</strong><span>Review recipient, asset, amount, and fee</span></div><div><strong>03</strong><span>Verify activity on Stellar Explorer</span></div></section>
    <section className="why-section" id="why-stellar"><div><div className="eyebrow">Built for learning in public</div><h2>A calmer way to understand cross-border payments.</h2></div><p>StellarRemit keeps the important details visible: the network, the asset, the destination, and the estimated fee. The codebase is open for contributors to improve through focused GitHub issues.</p></section>
    <footer className="landing-footer"><span>StellarRemit · Testnet MVP</span><div><Link href="/dashboard">Dashboard</Link><a href="https://github.com/jamixy/stellar-remit">GitHub</a><a href="https://github.com/jamixy/stellar-remit/tree/main/docs">Documentation</a></div></footer>
  </main>;
}